[google]
type = "service_account"
project_id = "diamond-pricing-453216"
private_key_id = "d905a21505f6a864b08eb480f4d4bec932f4fc7a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFBWpnvgyHDK4J
ZKRb30AAf5aOk3CUfadcU+Gi1JO2tGYs6yIfwgqTuXtaAgKOlHinrSNQwef17xMT
UVaW4mkIBO7QEPtzqZt8cN/Ub0lI4kjUIzqHrn13csIpaCG/gnxLyA34fD1nBIXF
In/8oa+Pd9+dk7XHdXEI+5KopicET4z1G+22P/dc9r+c98616mXTuUimpmB1BSyU
Y32lh5sD50VcnTFToNJphsxlinBgPqlrQsx6nsgaI2y3IcLzOHoBDGx0TJ+sRcOr
TbsmlK5wDMdfpJ5PTfl0D9jMUjRBHQKPVfEspK5ELP5yNXybP+6hlLeKuqmUcPrA
PVbiY+jPAgMBAAECggEAB4FwpPRyhGU77r5Xces2rvjYAs/PHCO6pSPKQWpubilq
iGTfb0JJ0N2Mu3MUJzEKH6koN+1gftgAFrOkjtRKmAmdZ25zhdvSQT1ePuOLxoEI
W+czqvOUyAt70MQCH8pCyJ2dxUzxBzmpjEcHhSz2WTWB3qjqkJICymAlyChRmDJh
KjzZfsE5GQelTYWoQERmx3OsrPdOw1rIjpZVdMOtXvgMUFlgDViCdPahmECu4Aw/
G1DDQTv0FceOBedYmiMuXIRMviHJt/4WebnUbME9dqQ66jVfRM5GJ+JzusVCtmi1
AaRPlhAwH/qY339G1dn28DDpNGO4JGC9CcpawTrgUQKBgQDrcTW2mR5UjKDyoHFh
w4ljUMjLX58eIb2SZmbgJeDOL92G11KCIOAGnFvC/jL/CB+DXROibT6hRuhjVTEW
q5jF7nx8UH7HjY5lbXdlvzZfkW5un6nVGeyxevYgz3gF7v0Ho9rP8bTC6b+vHvxz
KdswTkOVGA6Me+WNu22j41lqSwKBgQDWOWNE5O+c+jsJ6QNWq35L39wJjORJo9oI
pFwJzTCYd+IIlG5B9PfpqNOvw6obwO+XBwUiVACFQS/YoXDcQGZv0GR4VSwf/I6l
sc8j/U+5uZmbbBM+SYYqBByymUpFu6kY9iV8/xQys6DVKPZams4AetfchXG/+4n7
WpgjAkqpDQKBgQDNSzyzyFW7EZhxl1bmETMl51X+h5VeF7uOAT5o6n5YK0J1hiFK
mFHfUc1tfGuJF1MrHyi0s58tz39oxer0wpGG3UmsuB+j7xmf9VBr5swJju0FBrF2
wJEzvG0K9PzJ57a4R7bPJQoh/uIGV/V2kaOvPj8NrRlag9oIuMqEYgQgewKBgQCA
Khta94DnsMmrly25J6bK7CZvzEw0RoRGkVbDQnCld2vS6ELC0TWVJL1pNa3LJvXw
rHGE5S7eim5+s6+bBiiDEvFZENPyWx5YwXWFOaL+Ia1l0BX/OOu8rXMh4xYNfEWh
unoZO16xKsi5XuVstZszrEsDEw9H5czahYvpvhA+7QKBgQDcp9x3eB9adfGCojTg
4xz+JXTZmGCFyIZ/X83PyqLgCK0GAoBh6ev74yqHyXIm5qJjVds1xge0rcZQflfZ
DGKPazJefpvxqtvZdyh/wPiIoonimTZmiVBfuHj/kBaR5AHLM7Ij7QWMNHMtvt1Q
tEaJ7y/jhxJZyxL5h+6tXu8gnQ==
-----END PRIVATE KEY-----"""
client_email = "diamond-pricing-update@diamond-pricing-453216.iam.gserviceaccount.com"
client_id = "103163756261265755225"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/diamond-pricing-update%40diamond-pricing-453216.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
